# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.product_repository:
        class: AppBundle\Service\ProductRepository
        arguments: ['@logger']
