# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.product_repository:
        class: AppBundle\Service\ProductRepository
        arguments: ['@logger', '@app.pdo']

    app.pdo:
        class: PDO
        arguments:
            - 'mysql:host=localhost;dbname=chicago_training'
            - 'root'
        calls:
            # $pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
            - [ setAttribute, [3, 2] ]

    app.product_serialization_subscriber:
        class: AppBundle\Serializer\ProductSerializerSubscriber
        tags:
            - { name: jms_serializer.event_subscriber }
